version: "3.8"

services:
  nginx:
    image: nginx:latest
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/templates/nginx.conf.template
      - "${HOST_STATIC_ROOT}:${NGINX_STATIC_ROOT}:ro"
    ports:
      - "80:80"
    command: >
      /bin/bash -c "envsubst \"`for v in $$(compgen -v);do printf '$${%s} ' $$v;done`'\"
      < /etc/nginx/templates/nginx.conf.template
      > /etc/nginx/conf.d/default.conf
      && nginx -g 'daemon off;'"
    depends_on:
      - portal
      - webapp

  webapp:
    image: ghcr.io/reframework/px-web-app:${WEBAPP_VERSION:-latest}
    restart: unless-stopped

  portal:
    image: ghcr.io/reframework/px-api-portal:${PORTAL_VERSION:-latest}
    restart: unless-stopped
    ports:
      - "80:8000"
    env_file:
      - .env
