version: "3.8"

services:
  webapp:
    image: ghcr.io/reframework/px-web-app:${WEBAPP_VERSION:-latest}
    restart: unless-stopped

  portal:
    image: ghcr.io/reframework/px-api-portal:${PORTAL_VERSION:-latest}
    restart: unless-stopped
    ports:
      - "80:8000"
    env_file:
      - .env

volumes:
  caddy:
    driver: local
