version: "3.8"

services:
  webapp:
    image: ghcr.io/reframework/px-web-app:${WEBAPP_VERSION:-latest}
    restart: unless-stopped

  portal:
    image: ghcr.io/reframework/px-api-portal:${PORTAL_VERSION:-latest}
    restart: unless-stopped
    ports:
      - "80:80"
    env_file:
      - .env
    depends_on:
      - migrate

  postgres:
    image: ghcr.io/reframework/px-postgres:${POSTGRES_VERSION:-latest}
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres

  migrate:
    image: ghcr.io/reframework/px-api-migration:${MIGRATE_VERSION:-latest}
    restart: on-failure
    env_file:
      - .env
    depends_on:
      - postgres

volumes:
  caddy:
    driver: local
