version: "3.8"

services:
  admin:
    image: ghcr.io/reframework/shopana-cms-client:latest
    restart: unless-stopped
    ports:
      - "80:8080"

  api:
    image: ghcr.io/reframework/shopana-cms-api:latest
    restart: unless-stopped
    ports:
      - "80:8000"
    env_file:
      - .env


volumes:
  caddy:
    driver: local
