name: Portainer Webhook

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  buildkite:
    name: Buildkite
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Trigger a Buildkite Build
        uses: "buildkite/trigger-pipeline-action@v2.0.0"
        with:
          buildkite_api_access_token: ${{ secrets.RFW_BUILDKITE_TOKEN }}
          pipeline: "reframework/deploy-stack"
          branch: "main"
          commit: "HEAD"
          message:  ":traefik: Deploy stack: ${{ github.event.pull_request.title }}"
          ignore_pipeline_branch_filter: true
